package entity;

public enum SqlQueries {
    INSERT,
    INSERT_POSTER,
    GET_BY_ID,
    GET_BY_USER_ID,
    GET_BY_FIELD,
    GET_BY_FIELD_NAME,
    GET_BY_TEMPLATE,
    GET_BY_USERNAME_PASSWORD,
    GET_ALL,
    GET_ALL_LIMIT,
    UPDATE_BY_ID,
    UPDATE_BY_FIELD,
    DELETE_BY_ID,
    DELETE_BY_FIELD
}
